SUPABASE_URL = "https://hlvxvwvzbswmkebtesuv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsdnh2d3Z6YnN3bWtlYnRlc3V2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODEyMDYxMCwiZXhwIjoyMDgzNjk2NjEwfQ.s_CxM1SsPyWO-XY-aXWaQn_rUP3GTsVhMz3V-7GOX0k"  
  
  [postgres]
host = "db.hlvxvwvzbswmkebtesuv.supabase.co"
dbname = "postgres"
user = "postgres"  
password = "Blueisredindeed27"
port = 5432



